export type Challenge = {
  id: number
  word: string
  tip: string
}

export const WORDS: Challenge[] = [
  { id: 1, word: "CSS", tip: "Linguagem de estilos" },
  { id: 2, word: "REACT", tip: "Biblioteca para criar interfaces Web" },
  { id: 3, word: "HTML", tip: "Linguagem de marcação" },
  { id: 4, word: "JAVASCRIPT", tip: "Uma das linguagens de programação mais utilizadas no mundo" },
  { id: 5, word: "TYPESCRIPT", tip: "Para adicionar tipagem no Javascript" },
  { id: 6, word: "NODE", tip: "Ambiente de execução JavaScript no servidor" },
  { id: 7, word: "VUE", tip: "Framework progressivo para interfaces" },
  { id: 8, word: "ANGULAR", tip: "Framework front-end mantido pelo Google" },
  { id: 9, word: "API", tip: "Interface de comunicação entre sistemas" },
  { id: 10, word: "JSON", tip: "Formato leve de troca de dados" },
  { id: 11, word: "HTTP", tip: "Protocolo de comunicação da web" },
  { id: 12, word: "GIT", tip: "Sistema de controle de versão" },
  { id: 13, word: "DOCKER", tip: "Ferramenta de conteinerização" },
  { id: 14, word: "LINUX", tip: "Sistema operacional de código aberto" },
  { id: 15, word: "MYSQL", tip: "Banco de dados relacional popular" },
  { id: 16, word: "POSTGRES", tip: "Banco de dados relacional avançado" },
  { id: 17, word: "MONGODB", tip: "Banco de dados NoSQL orientado a documentos" },
  { id: 18, word: "EXPRESS", tip: "Framework web minimalista para Node" },
  { id: 19, word: "TAILWIND", tip: "Framework CSS utilitário" },
  { id: 20, word: "BOOTSTRAP", tip: "Framework CSS com componentes prontos" },
  { id: 21, word: "PRISMA", tip: "ORM moderno para Node.js" },
  { id: 22, word: "JWT", tip: "Token usado para autenticação" },
  { id: 23, word: "AUTH", tip: "Abreviação comum para autenticação" },
  { id: 24, word: "CACHE", tip: "Armazenamento temporário de dados" },
  { id: 25, word: "REDIS", tip: "Banco de dados em memória" },
  { id: 26, word: "QUEUE", tip: "Fila de processamento de tarefas" },
  { id: 27, word: "WORKER", tip: "Processo que executa tarefas em segundo plano" },
  { id: 28, word: "TEST", tip: "Verificação automática de código" },
  { id: 29, word: "VITEST", tip: "Framework de testes para Vite" },
  { id: 30, word: "JEST", tip: "Framework de testes para JavaScript" },
  { id: 31, word: "CI", tip: "Integração contínua" },
  { id: 32, word: "CD", tip: "Entrega contínua" },
  { id: 33, word: "PIPELINE", tip: "Fluxo automatizado de build e deploy" },
  { id: 34, word: "CLOUD", tip: "Computação em nuvem" },
  { id: 35, word: "AWS", tip: "Plataforma de serviços em nuvem da Amazon" },
  { id: 36, word: "AZURE", tip: "Plataforma de nuvem da Microsoft" },
  { id: 37, word: "GCP", tip: "Plataforma de nuvem do Google" },
  { id: 38, word: "SERVER", tip: "Computador que fornece serviços" },
  { id: 39, word: "CLIENT", tip: "Aplicação que consome serviços" },
  { id: 40, word: "FRONTEND", tip: "Parte visual de uma aplicação" },
  { id: 41, word: "BACKEND", tip: "Parte lógica e de dados de uma aplicação" },
  { id: 42, word: "FULLSTACK", tip: "Desenvolvedor que atua no front e back" },
  { id: 43, word: "ROUTER", tip: "Responsável por rotas em aplicações" },
  { id: 44, word: "MIDDLEWARE", tip: "Camada intermediária no processamento" },
  { id: 45, word: "DATABASE", tip: "Local onde os dados são armazenados" },
  { id: 46, word: "SCHEMA", tip: "Estrutura de dados de um banco" },
  { id: 47, word: "MODEL", tip: "Representação de dados na aplicação" },
  { id: 48, word: "CONTROLLER", tip: "Camada que controla requisições" },
  { id: 49, word: "SERVICE", tip: "Camada de regras de negócio" },
  { id: 50, word: "REPOSITORY", tip: "Camada de acesso a dados" },
]